### ISSUE TITLE
F-Droid loops pending download, and no asset other than source.

### ISSUE THREAD

**Issue by paramounttrivials** [k3b/CameraFolder#3]
Hi, 

What should i do to compile this apk? I am thinking just download the sdk from google and load the source? 

Unless there is an easier or alternative way with perks, would you suggest this?

Thank you, 

Jeremy

**Comment by k3b** [comment]
@paramounttrivials 

on the commandline execute 

       ./gradlew assemble test

I will add this info to the readme page.

**Comment by paramounttrivials** [comment]
Ok, thanks.
